parameters:
    profile_photos_directory: '%kernel.project_dir%/public/uploads/photos'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Enregistre tous les services dans src/
    App\:
        resource: '../src/'

    # Enregistre tous les contrôleurs avec autowiring complet
    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']